### ISSUE TITLE
Documentation: encoding?  

### ISSUE THREAD

**Issue by jsfenfen** [esonderegger/fecfile#8]
Hey @esonderegger I'm finally running some stuff with this library! Thanks for all your work. 

One thing I noted is that some filings appear to not be UTF-8. This is external to your library, but causes it to crash and burn. Example: 1260488.fec fails with: 'utf-8' codec can't decode byte 0x92 in position 1062: invalid start byte. 

This works fine if one just opens with the qwarg encoding = "ISO-8859-1", but I don't have good metrics yet on what encoding works best for all filings. Can update with more complete stats in a bit.

**Comment by esonderegger** [comment]
Thanks for trying out the library and thank you so much for finding and reporting this issue!

Interestingly enough, calling `fecfile.from_http(1260488)` worked properly, so I think the issue was just with trying to read the files from the bulk data zips.

I did a little bit of spot checking, and it appears as though UTF-8 is the much more common encoding, so I fixed this by first trying to read the file as UTF-8 and then trying to read the file as ISO-8859-1 if that fails.

This should be fixed in #9 and in version 0.4.11, which is now available on pypi. Please let me know if you run into any more issues while using this.

Thanks again!
